name: 'Create or Update Comment'
description: 'Create or update an issue or pull request comment'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    required: true
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
    required: false
  issue-number:
    description: 'The number of the issue or pull request in which to create a comment.'
    required: false
  comment-id:
    description: 'The id of the comment to update.'
    required: false
  body:
    description: 'The comment body.'
    required: false
  edit-mode:
    description: 'The mode when updating a comment, "replace" or "append".'
    default: 'append'
    required: false
  reaction-type:
    description: 'The reaction to add to the comment.'
    required: false
outputs:
  repository:
    description: 'The full name of the repository in which comment was created'
  issue-number:
    description: 'The number of the issue or pull request in which comment was created'
  comment-id:
    description: 'The id of the comment created'
  body:
    description: 'The comment body of the comment created'
  reaction-type:
    description: 'The reaction added to the comment created'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'
